<<<<<<< HEAD
server.port: 8081
=======
>>>>>>> bb6e2f0 (setup basic authentication and recording admin account into database, but not done)
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/user
    username: root
    password: password
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
<<<<<<< HEAD
      ddl-auto: create
=======
      ddl-auto: update
>>>>>>> bb6e2f0 (setup basic authentication and recording admin account into database, but not done)
